# Site
name: "Capita Byte"
title: "Capita Byte"
description: "Translating tech talk, from byte to capita insights."
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.png'  # to be updated
google_analytics: 'G-LEJB0MZ2VN'  # GDPR note to be updated
disqus: 'ByteExchange'
mailchimp-list: ''  # list to be updated, if applicable
include: ["_pages"]
permalink: /:title/
email: info@capitabyte.com

# Authors
authors:
authors:
  mehrdad:
    name: Mehrdad
    display_name: Mehrdad Touraji
    avatar: 'assets/images/mehrdad.jpg'
    email: mehrdad.touraji@gmail.com
    web: https://mtouraji.streamlit.app/
    twitter: https://twitter.com/  #to be updated
    description: "Data engineer, software developer, and tech enthusiast. Exploring the intersection of data and decision-making."


# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
highlighter: rouge
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-73558265166947456"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
